// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oil_Payment_Calculator.Data;

#nullable disable

namespace Oil_Payment_Calculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206141122_SeedApartments")]
    partial class SeedApartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oil_Payment_Calculator.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Όροφος Δημήτρη",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Καταστημα - Ισογειο Δημήτρη",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Υπογειο Δημήτρη",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Όροφος Νικου",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Καταστημα - Ισογειο Νικου",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Υπογειο Νικου",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Oil_Payment_Calculator.Models.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentReading")
                        .HasColumnType("int");

                    b.Property<int>("PreviousReading")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("Oil_Payment_Calculator.Models.MeterReading", b =>
                {
                    b.HasOne("Oil_Payment_Calculator.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });
#pragma warning restore 612, 618
        }
    }
}
